# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
